const recipes = [
	{
		id: "vegan-cinnamon-rolls",
		name: "The Best Ever Vegan Cinnamon Rolls",
		category: "Dessert",
		image: "cinnamon_roll.jpg",
		source: "https://tasty.co/recipe/the-best-ever-vegan-cinnamon-rolls",
		prep_time: "20 min + rise time",
		cook_time: "25 min",
		servings: 9,
		nutrition: { calories: 310, protein: 4, carbs: 52, fat: 10, fiber: 1 },
		ingredients: [
			"1 cup unsweetened almond milk",
			"1/4 cup vegan butter, melted",
			"2 tbsp sugar",
			"1 packet active dry yeast",
			"3 cups all-purpose flour (plus more as needed)",
			"1 tsp baking powder",
			"1/2 tsp salt",
			"3/4 cup brown sugar",
			"1/4 cup vegan butter (for filling)",
			"2 tbsp ground cinnamon",
			"1 cup powdered sugar",
			"2 tbsp almond milk (for glaze)",
			"1/2 tsp vanilla extract"
		],
		instructions: [
			"Warm the almond milk until just warm, not hot.",
			"Mix almond milk, melted butter, and sugar.",
			"Add yeast and let it foam.",
			"Mix in flour, baking powder, and salt to form dough.",
			"Knead until smooth and let rise.",
			"Roll dough into a rectangle.",
			"Spread butter, sugar, and cinnamon over the dough.",
			"Roll and slice.",
			"Let rise again.",
			"Bake until golden.",
			"Mix glaze and pour over rolls."
		]
	},
	{
		id: "tofu-scramble-spinach-sun-dried-tomatoes",
		name: "Tofu Scramble with Spinach & Sun-Dried Tomatoes",
		category: "Breakfast",
		image: "tofu_scramble.jpg",
		source: "https://www.walmart.com/i/recipes/Tofu-scramble-with-spinach-and-sun-dried-tomatoes/1995152",
		prep_time: "10 min",
		cook_time: "15 min",
		servings: 2,
		nutrition: { calories: 260, protein: 18, carbs: 14, fat: 15, fiber: 4 },
		ingredients: [
			"14 oz firm tofu",
			"1 tbsp olive oil",
			"1/2 onion, diced",
			"2 cloves garlic, minced",
			"1/4 cup sun-dried tomatoes, chopped",
			"2 cups fresh spinach",
			"1/2 tsp curry powder",
			"1/2 tsp cumin",
			"1/2 tsp smoked paprika",
			"Salt to taste",
			"Black pepper to taste"
		],
		instructions: [
			"Drain the tofu: line a plate with a clean dish towel or 4 layers of paper towels. Set the tofu on top of the towel(s) and fold the rest of the towel(s) on top of the tofu to cover. Put another plate on top of those towels and place something heavy on the top of the stack. Let sit for at least a few minutes to remove some of the water from the tofu.",
			"Dice onion; mince garlic; crumble tofu; chop sun-dried tomatoes.",
			"Heat olive oil in a skillet over medium heat.",
			"Add diced onions and cook until softened, about 6 minutes.",
			"Stir in minced garlic and cook for an additional 30 seconds.",
			"Add crumbled tofu to the skillet, along with curry, cumin, smoked paprika, salt, and pepper. Mix well.",
			"Cook the tofu mixture for 5-7 minutes, allowing it to absorb the flavors and develop a golden color.",
			"Add fresh spinach and sun-dried tomatoes to the skillet. Cook until the spinach is wilted.",
			"Taste and adjust the seasonings as needed."
		]
	},
	{
		id: "tofu-protein-pancakes",
		name: "Whipped Tofu Protein Pancakes",
		category: "Breakfast",
		image: "tofu_pancakes.jpg",
		source: "https://www.veganricha.com/wp-content/uploads/2025/08/Whipped-Tofu-Recipes-Printable-Vegan-Richa-REVISION-2-5.pdf",
		prep_time: "10 min",
		cook_time: "5 min",
		servings: 4,
		nutrition: { calories: 195, protein: 11, carbs: 26, fat: 5, fiber: 2 },
		ingredients: [
			"14 oz firm or extra firm tofu",
			"Scant 1 cup water (1 tbsp less than 1 cup)",
			"1/2 cup flour",
			"2 tbsp almond flour",
			"1 tsp baking powder",
			"1/2 tsp vanilla powder or extract",
			"1/4 cup sweet whipped tofu mixture",
			"1-2 tbsp maple syrup",
			"6-7 tbsp non-dairy milk",
			"Berries, chocolate chips, or cinnamon (optional)"
		],
		instructions: [
			"Blend tofu and water until smooth and creamy to create the whipped tofu base. No salt, flour, or cornstarch needed. Chill in the fridge for a few hours to let it thicken if you want a thicker base.",
			"Mix the flour, almond flour, baking powder, and vanilla powder, if using, well. Press and mix to break up and blend in the almond flour evenly.",
			"Stir in the vanilla extract, if using, 1/4 cup of the whipped tofu, maple syrup, and 6 tablespoons of the non-dairy milk to make a thick batter.",
			"If the batter is too thick, add a little more milk to thin it out, but do not thin it too much. Keep the batter thicker than regular pancake batter.",
			"Heat a skillet over medium-high heat and add some oil or vegan butter.",
			"Once the oil is hot, spread the batter onto the skillet. The batter will be thick, so use a spatula to spread it out.",
			"Press in the berries and chocolate chips, if using.",
			"Cook for 2 minutes until golden, then flip and cook another 1-2 minutes.",
			"Serve with fruit, maple syrup, butter, and your favorite toppings."
		]
	},
	{
		id: "smashed-chickpea-caesar-wraps",
		name: "Smashed Chickpea Caesar Wraps",
		category: "Lunch",
		image: "chickpea_wrap.jpg",
		source: "https://www.liveeatlearn.com/smashed-chickpea-caesar-wraps",
		prep_time: "15 min",
		cook_time: "15 min",
		servings: 2,
		nutrition: { calories: 420, protein: 16, carbs: 48, fat: 18, fiber: 8 },
		ingredients: [
			"1 (15 oz) can chickpeas, drained and patted dry with paper towels",
			"1/4 medium white onion",
			"1 tbsp flour",
			"1/2 tsp garlic powder",
			"1/2 tsp salt",
			"1/2 tsp smoked paprika",
			"2 tbsp olive oil",
			"2 tortilla wraps",
			"2 handfuls chopped romaine",
			"2-4 tbsp Caesar dressing",
			"2 tbsp parmesan cheese"
		],
		instructions: [
			"Add the chickpeas, white onion, flour, garlic powder, salt, and smoked paprika to a food processor. Blitz until it forms a thick dough.",
			"Scoop the mixture evenly onto the 2 tortilla wraps.",
			"Spread the mixture evenly over the entire wrap, leaving a small border around the edges.",
			"Working in batches, heat the olive oil in a large pan over medium heat.",
			"Carefully transfer a wrap to the pan, laying it chickpea-side down. Cook for 8-10 minutes, or until the chickpea layer is golden brown.",
			"Flip the chickpea wrap out of the pan. If the chickpea layer seems fragile, hold a plate or cutting board over the pan like a lid, then flip the whole thing over so the wrap lands smoothly on the plate.",
			"Arrange chopped romaine, Caesar dressing, and parmesan cheese in mounds on the wraps.",
			"Fold the sides over the fillings, then roll up the wrap, tucking the side closest to you over the fillings and rolling away from you.",
			"Firmly squeeze the wrap to contain everything, then slice in half and enjoy."
		]
	},
	{
		id: "slow-cooker-black-bean-soup",
		name: "Slow Cooker Black Bean Soup",
		category: "Dinner",
		image: "black_bean_soup.jpg",
		source: "https://www.connoisseurusveg.com/slow-cooker-black-bean-soup/#recipe",
		prep_time: "15 min + soak",
		cook_time: "3.5–4 hrs (high) or 6–7 hrs (low)",
		servings: 6,
		nutrition: { calories: 290, protein: 17, carbs: 50, fat: 2, fiber: 16 },
		ingredients: [
			"1 lb dried black beans",
			"5 cups vegetable broth (plus more as needed)",
			"1 medium onion, diced",
			"2 medium carrots, sliced",
			"2 celery stalks, chopped",
			"3 garlic cloves, minced",
			"1 tbsp ground cumin",
			"1 tsp smoked paprika",
			"1 tsp dried oregano",
			"1 bay leaf",
			"2 tbsp lime juice",
			"1 tsp salt (or to taste)",
			"Black pepper to taste"
		],
		instructions: [
			"Place dried beans in a large bowl and cover with water (at least 3x the volume). Soak overnight for 8–12 hours.",
			"Drain and rinse the beans the next day.",
			"Add beans to a slow cooker (3-quart or larger) along with broth, onion, carrots, celery, garlic, cumin, smoked paprika, oregano, and bay leaf.",
			"Stir well, cover, and cook on high for 3.5–4 hours or low for 6–7 hours, until beans are very tender.",
			"Remove lid and discard bay leaf.",
			"Optional: Blend about half the soup using an immersion blender or standard blender, then return it to the pot.",
			"If needed, add more broth or hot water to reach desired consistency.",
			"Stir in lime juice, then season with salt and pepper to taste.",
			"Ladle into bowls and serve."
		]
	}
];
